version: 2.1
orbs:
  python: circleci/python@1.5.0


jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m vent vent && source ./venv/bin/activate && pip install -r requirements.txt && python manage.py collectstatic && python manage.py runserver
     



workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: master # only deploy when on main
