version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Create environment
          command: |
             python3 -m venv venv
             source ./venv/bin/activate
      
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip3 install --user -r requirements.txt
      - run:
          name: Run web server
          command: |
            cd ~
            python3 manage.py collectstatic
            python3 manage.py runserver
            
     
workflows:
  build_test:
    jobs:
      - run_tests
      
      
     
